---
- name: Verify - K3s
  hosts: k3s_server:k3s_agent
  gather_facts: no
  vars:
    ansible_libvirt_uri: >-
      {% if hostvars[groups['hypervisor'] | first].ansible_connection == 'ssh' %}qemu+ssh://{{ hostvars[groups['hypervisor'] | first].ansible_user }}@{{ hostvars[groups['hypervisor'] | first].ansible_host }}/system{% else %}qemu:///system{% endif %}
    ansible_connection: "community.libvirt.libvirt_qemu"
  become: yes
  serial: "{{ lookup('env', 'ANSIBLE_SERIAL') }}"
  tasks:
    - name: Get Cluster info
      ansible.builtin.shell: "/usr/local/bin/kubectl get node"
      failed_when: false
      register: output_get_node

    - assert:
        that: output_get_node.rc != 0

    - debug:
        var: output_get_node.stderr