---
- set_fact:
    scale_down_node_names: "{{ scale_down_node_names | default ([]) + [ hostvars[item].ansible_hostname ] }}"
  loop: "{{ groups['scale_down_host'] }}"

- name: Cordon node
  ansible.builtin.shell: "/usr/local/bin/kubectl cordon {{ item }}"
  loop: "{{ scale_down_node_names }}"
  register: output_cordon
  until: output_cordon.rc == 0
  retries: 10

- name: Delete node
  ansible.builtin.shell: "/usr/local/bin/kubectl delete node {{ item }}"
  loop: "{{ scale_down_node_names }}"
  register: output_delete
  until: output_delete.rc == 0
  retries: 10